plugins { id 'com.android.application' }
android {
    namespace 'com.dogra.mustang'
    compileSdk 35
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
    defaultConfig {
        applicationId 'com.dogra.mustang'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    lint { abortOnError true }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
