package com.dogra.mustang;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaMetadataRetriever;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.util.Rational;
import android.view.*;
import android.widget.*;
import android.text.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity implements SurfaceHolder.Callback {
    static final int BG=0xff101411,CARD=0xff202820,INK=0xfff2f5ed,MUTED=0xffa1b29d,ACCENT=0xffd6f57c;
    static final String[] LANGUAGES={"All languages","Hindi","Punjabi","English","Bhojpuri","Tamil","Telugu","Bengali","Marathi","Gujarati","Kannada","Malayalam","Urdu","Other","Instrumental"};
    private Library library;
    private LinearLayout page,queue,lyricBox,videoBox;
    private ScrollView scroll,lyricScroll;
    private SurfaceView surface;
    private TextView title,status,clock,empty,credit;
    private Button toggle,quality;
    private SeekBar seek;
    private EditText search;
    private Spinner language,kind;
    private Switch autoScroll;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private boolean active,dragging;
    private String shownId="",shownLyrics="",currentFilter="",lyricsTarget="",variantTarget="";
    private int lastLine=-2;
    private Lyrics lyrics=new Lyrics("");
    private final List<TextView> lyricViews=new ArrayList<>();
    private final Map<String,View> rows=new HashMap<>();
    private boolean importsBusy;
    private final Runnable tick=new Runnable(){public void run(){if(!active)return;refreshPlayer();handler.postDelayed(this,350);}};

    public void onCreate(Bundle saved){super.onCreate(saved);library=Library.get(this);if(saved!=null){lyricsTarget=saved.getString("lyricsTarget","");variantTarget=saved.getString("variantTarget","");}build();seed();renderQueue();}
    protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("lyricsTarget",lyricsTarget);b.putString("variantTarget",variantTarget);}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(dp(5),dp(5),dp(5),dp(5));return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private void card(View v){GradientDrawable d=new GradientDrawable();d.setColor(CARD);d.setCornerRadius(dp(18));v.setBackground(d);v.setPadding(dp(12),dp(10),dp(12),dp(10));}
    private Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextColor(INK);b.setAllCaps(false);b.setTextSize(13);b.setOnClickListener(v->action.run());return b;}
    private void addEqual(LinearLayout r,View v){r.addView(v,new LinearLayout.LayoutParams(0,-2,1));}
    private Spinner spinner(String[] options){Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,options);s.setAdapter(a);return s;}
    private void build(){
        scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);page=col();page.setPadding(dp(16),dp(20),dp(16),dp(28));scroll.addView(page);setContentView(scroll);
        page.setOnApplyWindowInsetsListener((v,insets)->{page.setPadding(dp(16),dp(16)+insets.getSystemWindowInsetTop(),dp(16),dp(24)+insets.getSystemWindowInsetBottom());return insets;});
        LinearLayout brand=row();ImageView horse=new ImageView(this);horse.setImageResource(R.drawable.ic_mustang);horse.setContentDescription("Mustang horse logo");brand.addView(horse,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout names=col();TextView word=text("MUSTANG",25,ACCENT);word.setTypeface(null,Typeface.BOLD);names.addView(word);names.addView(text("Music. Video. Your languages.",12,MUTED));brand.addView(names);page.addView(brand);
        LinearLayout imports=row();addEqual(imports,button("＋ Files",()->pick(10,new String[]{"audio/*","video/*"})));addEqual(imports,button("＋ Stream",()->streamDialog(null)));page.addView(imports);
        LinearLayout filters=row();kind=spinner(new String[]{"All media","Music","Videos"});language=spinner(LANGUAGES);addEqual(filters,kind);addEqual(filters,language);page.addView(filters);
        search=new EditText(this);search.setSingleLine();search.setTextColor(INK);search.setHintTextColor(MUTED);search.setHint("Search title or artist");page.addView(search);
        AdapterView.OnItemSelectedListener selected=new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int pos,long id){renderQueue();}public void onNothingSelected(AdapterView<?>p){}};kind.setOnItemSelectedListener(selected);language.setOnItemSelectedListener(selected);
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){renderQueue();}public void afterTextChanged(Editable e){}});
        LinearLayout playerCard=col();card(playerCard);title=text("Choose a song or video",22,INK);title.setTypeface(null,Typeface.BOLD);playerCard.addView(title);status=text("Add files from your phone or a direct HTTPS stream.",13,MUTED);playerCard.addView(status);
        videoBox=col();surface=new SurfaceView(this);surface.getHolder().addCallback(this);videoBox.addView(surface,new LinearLayout.LayoutParams(-1,dp(200)));videoBox.setVisibility(View.GONE);playerCard.addView(videoBox);
        seek=new SeekBar(this);seek.setMax(1000);playerCard.addView(seek);clock=text("0:00 / 0:00",12,MUTED);playerCard.addView(clock);
        seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int progress,boolean user){}public void onStartTrackingTouch(SeekBar s){dragging=true;}public void onStopTrackingTouch(SeekBar s){PlaybackService p=PlaybackService.instance;if(p!=null)p.seek((int)((long)s.getProgress()*p.duration()/1000));dragging=false;}});
        LinearLayout transport=row();addEqual(transport,button("Previous",()->command("previous")));toggle=button("Play",()->command("toggle"));addEqual(transport,toggle);addEqual(transport,button("Next",()->command("next")));playerCard.addView(transport);
        LinearLayout more=row();quality=button("Quality",this::qualityDialog);addEqual(more,quality);addEqual(more,button("Mini video",this::pip));addEqual(more,button("Stop",()->command("stop")));playerCard.addView(more);
        Switch autoplay=new Switch(this);autoplay.setText("Auto-play next music / video");autoplay.setTextColor(INK);autoplay.setChecked(getSharedPreferences("settings",0).getBoolean("autoplay",true));autoplay.setOnCheckedChangeListener((b,on)->{getSharedPreferences("settings",0).edit().putBoolean("autoplay",on).apply();if(PlaybackService.instance!=null)PlaybackService.instance.autoplay=on;});playerCard.addView(autoplay);
        autoScroll=new Switch(this);autoScroll.setText("Auto-scroll queue and synced lyrics");autoScroll.setTextColor(INK);autoScroll.setChecked(getSharedPreferences("settings",0).getBoolean("scroll",true));autoScroll.setOnCheckedChangeListener((b,on)->getSharedPreferences("settings",0).edit().putBoolean("scroll",on).apply());playerCard.addView(autoScroll);page.addView(playerCard);
        LinearLayout lyricsHeading=row();addEqual(lyricsHeading,text("LYRICS",14,ACCENT));addEqual(lyricsHeading,button("Find",this::findLyrics));addEqual(lyricsHeading,button("Import LRC",()->{Track t=current();if(t==null){toast("Play a song first.");return;}lyricsTarget=t.id;pick(11,new String[]{"text/*","application/octet-stream"});}));page.addView(lyricsHeading);
        lyricScroll=new ScrollView(this);lyricBox=col();lyricScroll.addView(lyricBox);card(lyricScroll);page.addView(lyricScroll,new LinearLayout.LayoutParams(-1,dp(175)));
        credit=text("",11,MUTED);page.addView(credit);page.addView(text("YOUR LIBRARY  ·  long-press to edit",14,ACCENT));queue=col();page.addView(queue);empty=text("No matches. Add media or change your filters.",14,MUTED);page.addView(empty);page.addView(text("Background audio stays on when you leave. Mini video uses picture-in-picture. Formats depend on your phone.",12,MUTED));
    }
    private Track current(){return PlaybackService.instance==null?null:PlaybackService.instance.track;}
    private void command(String action){if(PlaybackService.instance==null&&!"play".equals(action)){toast("Choose a track first.");return;}Intent i=new Intent(this,PlaybackService.class).setAction(action);if("stop".equals(action)){stopService(i);refreshPlayer();}else startForegroundService(i);}
    private void play(Track t){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},90);startForegroundService(new Intent(this,PlaybackService.class).setAction("play").putExtra("id",t.id));}
    private void renderQueue(){if(queue==null)return;queue.removeAllViews();rows.clear();String query=search.getText().toString().toLowerCase(Locale.ROOT);String lang=String.valueOf(language.getSelectedItem());int mode=kind.getSelectedItemPosition();
        for(Track t:library.tracks){if(mode==1&&t.video||mode==2&&!t.video)continue;if(!"All languages".equals(lang)&&!lang.equals(t.language))continue;if(!(t.title+" "+t.artist).toLowerCase(Locale.ROOT).contains(query))continue;
            LinearLayout entry=row();card(entry);TextView glyph=text(t.video?"▶":"♫",24,ACCENT);entry.addView(glyph,new LinearLayout.LayoutParams(dp(42),-2));LinearLayout info=col();info.addView(text(t.title,17,INK));info.addView(text(t.language+" · "+(t.artist.isEmpty()?t.video?"Video":"Music":t.artist),12,MUTED));entry.addView(info,new LinearLayout.LayoutParams(0,-2,1));entry.setContentDescription("Play "+t.title);entry.setOnClickListener(v->play(t));entry.setOnLongClickListener(v->{edit(t);return true;});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(8);queue.addView(entry,lp);rows.put(t.id,entry);
        }empty.setVisibility(rows.isEmpty()?View.VISIBLE:View.GONE);currentFilter=query+lang+mode;
    }
    private void refreshPlayer(){PlaybackService p=PlaybackService.instance;Track t=p==null?null:p.track;
        if(t==null){title.setText("Choose a song or video");status.setText("Add files from your phone or a direct HTTPS stream.");toggle.setText("Play");videoBox.setVisibility(View.GONE);seek.setProgress(0);clock.setText("0:00 / 0:00");quality.setText("Quality");if(!shownId.isEmpty()||lyricViews.isEmpty()){shownId="";shownLyrics="";drawLyrics("");}return;}
        title.setText(t.title);status.setText(p.status+" · "+t.language);toggle.setText(p.playing()?"Pause":"Play");quality.setText(t.video?"Quality · "+p.quality:"Source · "+p.quality);videoBox.setVisibility(t.video?View.VISIBLE:View.GONE);
        if(surface.getHolder().getSurface().isValid())p.attach(surface.getHolder());clock.setText(time(p.position())+" / "+time(p.duration()));if(!dragging)seek.setProgress(p.duration()>0?(int)((long)p.position()*1000/p.duration()):0);
        if(!shownId.equals(t.id)){shownId=t.id;shownLyrics="";lastLine=-2;credit.setText(t.credit);if(autoScroll.isChecked()&&!isInPictureInPictureMode()){View row=rows.get(t.id);if(row!=null)scroll.post(()->scroll.smoothScrollTo(0,queue.getTop()+row.getTop()));}}
        if(!shownLyrics.equals(t.lyrics)||lyricViews.isEmpty()){shownLyrics=t.lyrics;drawLyrics(t.lyrics);}
        int line=lyrics.at(p.position());if(line!=lastLine){if(lastLine>=0&&lastLine<lyricViews.size())lyricViews.get(lastLine).setTextColor(MUTED);if(line>=0&&line<lyricViews.size()){TextView view=lyricViews.get(line);view.setTextColor(ACCENT);if(autoScroll.isChecked())lyricScroll.smoothScrollTo(0,Math.max(0,view.getTop()-dp(45)));}lastLine=line;}
    }
    private void drawLyrics(String source){lyrics=new Lyrics(source);lyricViews.clear();lyricBox.removeAllViews();lastLine=-2;if(!lyrics.lines.isEmpty()){for(Lyrics.Line line:lyrics.lines){TextView v=text(line.text(),17,MUTED);lyricViews.add(v);lyricBox.addView(v);v.setOnClickListener(view->{if(PlaybackService.instance!=null)PlaybackService.instance.seek((int)Math.min(Integer.MAX_VALUE,line.time()));});}}
        else {TextView v=text(source.trim().isEmpty()?"Lyrics not added. Use Find or import an LRC / TXT file.":source,16,MUTED);lyricViews.add(v);lyricBox.addView(v);}}
    private static String time(int ms){int sec=ms/1000;return String.format(Locale.ROOT,"%d:%02d",sec/60,sec%60);}
    private void pick(int request,String[] mime){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_MIME_TYPES,mime).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);if(request==10)i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,request);}
    protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());
        for(Uri uri:uris)try{getContentResolver().takePersistableUriPermission(uri,data.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}
        if(request==11&&!uris.isEmpty()){String id=lyricsTarget;worker.execute(()->{try(InputStream in=getContentResolver().openInputStream(uris.get(0))){String text=readLimited(in,512000);handler.post(()->{Track t=library.find(id);if(t!=null){t.lyrics=text;library.save();shownLyrics="";refreshPlayer();}});}catch(Exception e){handler.post(()->toast("Could not read lyrics file."));}});}
        else if(request==12&&!uris.isEmpty()){Track t=library.find(variantTarget);if(t!=null)variantLabel(t,uris.get(0).toString());}
        else if(request==10){if(importsBusy){toast("Please wait for the current import.");return;}importsBusy=true;toast("Importing "+uris.size()+" files…");worker.execute(()->{List<Track> imported=new ArrayList<>();for(Uri uri:uris){Track t=new Track();t.title=displayName(uri);String mime=getContentResolver().getType(uri);t.video=mime!=null?mime.startsWith("video/"):t.title.toLowerCase(Locale.ROOT).matches(".*\\.(mp4|mkv|webm|mov|3gp)$");t.sources.put("Original",uri.toString());MediaMetadataRetriever m=new MediaMetadataRetriever();try{m.setDataSource(this,uri);String name=m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_TITLE),artist=m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_ARTIST);if(name!=null&&!name.trim().isEmpty())t.title=name;if(artist!=null)t.artist=artist;}catch(Exception ignored){}finally{m.release();}imported.add(t);}handler.post(()->{for(Track t:imported)library.add(t);importsBusy=false;renderQueue();toast("Added "+imported.size()+" items. Long-press to set language.");});});}
    }
    private String displayName(Uri uri){try(Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception ignored){}return "Imported media";}
    private EditText input(LinearLayout layout,String hint,String value){EditText e=new EditText(this);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(hint);e.setText(value);layout.addView(e);return e;}
    private void edit(Track t){LinearLayout fields=col();fields.setPadding(dp(18),0,dp(18),0);EditText name=input(fields,"Title",t.title),artist=input(fields,"Artist",t.artist);Spinner lang=spinner(Arrays.copyOfRange(LANGUAGES,1,LANGUAGES.length));for(int i=1;i<LANGUAGES.length;i++)if(LANGUAGES[i].equals(t.language))lang.setSelection(i-1);fields.addView(lang);
        new AlertDialog.Builder(this).setTitle("Edit media").setView(fields).setPositiveButton("Save",(d,w)->{if(!name.getText().toString().trim().isEmpty())t.title=name.getText().toString().trim();t.artist=artist.getText().toString().trim();t.language=String.valueOf(lang.getSelectedItem());library.save();renderQueue();}).setNeutralButton("Remove",(d,w)->new AlertDialog.Builder(this).setMessage("Remove from this library? Your file stays on your phone.").setNegativeButton("Cancel",null).setPositiveButton("Remove",(dd,ww)->{if(current()==t)stopService(new Intent(this,PlaybackService.class));library.tracks.remove(t);library.save();renderQueue();refreshPlayer();}).show()).setNegativeButton("Cancel",null).show();}
    private static boolean validUrl(String url){try{URI u=new URI(url);return "https".equalsIgnoreCase(u.getScheme())&&u.getHost()!=null&&u.getUserInfo()==null;}catch(Exception e){return false;}}
    private void streamDialog(Track target){LinearLayout fields=col();fields.setPadding(dp(18),0,dp(18),0);EditText name=input(fields,"Title",target==null?"":target.title),artist=input(fields,"Artist",target==null?"":target.artist);Spinner lang=spinner(Arrays.copyOfRange(LANGUAGES,1,LANGUAGES.length));fields.addView(lang);Switch video=new Switch(this);video.setText("Video");video.setTextColor(INK);fields.addView(video);EditText urls=input(fields,"One HTTPS URL, or one quality per line:\n360p=https://…\n720p=https://…","");urls.setMinLines(3);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Add your media stream").setMessage("Direct playable media links. YouTube/Spotify page links are not media files.").setView(fields).setPositiveButton("Add",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{Track t=new Track();t.title=name.getText().toString().trim();t.artist=artist.getText().toString().trim();t.video=video.isChecked();t.language=String.valueOf(lang.getSelectedItem());if(t.title.isEmpty()){name.setError("Enter a title");return;}for(String line:urls.getText().toString().split("\\R")){line=line.trim();if(line.isEmpty())continue;String label="Original",url=line;if(!line.startsWith("https://")&&line.contains("=")){int split=line.indexOf('=');label=line.substring(0,split).trim();url=line.substring(split+1).trim();}if(!validUrl(url)||label.isEmpty()||t.sources.containsKey(label)){urls.setError("Use unique labels and valid HTTPS media URLs.");return;}t.sources.put(label,url);}if(t.sources.isEmpty()){urls.setError("Add a media link");return;}library.add(t);renderQueue();dialog.dismiss();}));dialog.show();}
    private void qualityDialog(){Track t=current();if(t==null){toast("Play a video or song first.");return;}List<String> labels=new ArrayList<>(t.sources.keySet());labels.add("＋ Add quality file");labels.add("＋ Add quality stream");String[] values=labels.toArray(new String[0]);new AlertDialog.Builder(this).setTitle(t.video?"Available video qualities":"Available sources").setItems(values,(d,which)->{if(which<t.sources.size()){if(PlaybackService.instance!=null)PlaybackService.instance.quality(values[which]);}else if(which==t.sources.size()){variantTarget=t.id;pick(12,new String[]{t.video?"video/*":"audio/*"});}else{LinearLayout fields=col();EditText url=input(fields,"HTTPS media link","");AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Add quality stream").setView(fields).setPositiveButton("Next",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(x->dialog.getButton(-1).setOnClickListener(v->{String u=url.getText().toString().trim();if(!validUrl(u)){url.setError("Use HTTPS media URL");return;}dialog.dismiss();variantLabel(t,u);}));dialog.show();}}).show();}
    private void variantLabel(Track t,String uri){LinearLayout fields=col();EditText label=input(fields,"Quality label, e.g. 720p","");AlertDialog d=new AlertDialog.Builder(this).setTitle("Name this quality").setView(fields).setPositiveButton("Save",null).setNegativeButton("Cancel",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String name=label.getText().toString().trim();if(name.trim().isEmpty()||t.sources.containsKey(name)){label.setError("Use a new quality label");return;}t.sources.put(name,uri);library.save();d.dismiss();toast("Quality added. Choose it in Quality.");}));d.show();}
    private void findLyrics(){Track t=current();if(t==null){toast("Play a song first.");return;}LinearLayout fields=col();EditText name=input(fields,"Song title",t.title),artist=input(fields,"Artist",t.artist);new AlertDialog.Builder(this).setTitle("Find lyrics · LRCLIB").setMessage("Sends this title and artist to LRCLIB. Choose the matching recording; lyrics may not exist for every language or song.").setView(fields).setPositiveButton("Search",(d,w)->{String title=name.getText().toString().trim(),singer=artist.getText().toString().trim();if(title.isEmpty()){toast("Enter the song title.");return;}toast("Finding lyrics…");worker.execute(()->{try{String endpoint="https://lrclib.net/api/search?track_name="+URLEncoder.encode(title,"UTF-8")+"&artist_name="+URLEncoder.encode(singer,"UTF-8");HttpURLConnection connection=(HttpURLConnection)new URL(endpoint).openConnection();connection.setConnectTimeout(12000);connection.setReadTimeout(12000);connection.setRequestProperty("User-Agent","MustangPlayer/1.0 (https://github.com/dogra1212k/Music-player)");JSONArray results;try(InputStream in=connection.getInputStream()){results=new JSONArray(readLimited(in,2000000));}finally{connection.disconnect();}handler.post(()->{if(isFinishing()||isDestroyed())return;if(results.length()==0){toast("No lyrics found. Import LRC or TXT instead.");return;}String[] matches=new String[Math.min(results.length(),25)];for(int i=0;i<matches.length;i++){JSONObject j=results.optJSONObject(i);matches[i]=j.optString("trackName")+" — "+j.optString("artistName")+" · "+j.optString("albumName")+" · "+j.optInt("duration")+"s";}new AlertDialog.Builder(this).setTitle("Choose the correct recording").setItems(matches,(dd,index)->{if(library.find(t.id)==null)return;JSONObject match=results.optJSONObject(index);t.lyrics=match.optBoolean("instrumental")?"Instrumental — no sung lyrics.":match.optString("syncedLyrics","");if(t.lyrics.isEmpty())t.lyrics=match.optString("plainLyrics","");library.save();shownLyrics="";refreshPlayer();toast(t.lyrics.isEmpty()?"This recording has no lyrics yet.":"Lyrics saved for offline reading.");}).setNegativeButton("Cancel",null).show();});}catch(Exception e){handler.post(()->toast("Lyrics service unavailable. You can import LRC / TXT."));}});}).setNegativeButton("Cancel",null).show();}
    private static String readLimited(InputStream in,int limit)throws IOException{if(in==null)throw new IOException("No stream");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>limit)throw new IOException("File too large");out.write(buf,0,n);}return new String(out.toByteArray(),StandardCharsets.UTF_8);}
    private void pip(){Track t=current();if(t==null||!t.video){toast("Play a video first.");return;}try{enterPictureInPictureMode(new PictureInPictureParams.Builder().setAspectRatio(new Rational(16,9)).build());}catch(Exception e){toast("Mini video is unavailable on this phone.");}}
    public void onPictureInPictureModeChanged(boolean pip,android.content.res.Configuration c){super.onPictureInPictureModeChanged(pip,c);for(int i=0;i<page.getChildCount();i++)page.getChildAt(i).setVisibility(pip?View.GONE:View.VISIBLE);View parent=(View)videoBox.getParent();parent.setVisibility(View.VISIBLE);LinearLayout card=(LinearLayout)parent;for(int i=0;i<card.getChildCount();i++)card.getChildAt(i).setVisibility(pip?View.GONE:View.VISIBLE);videoBox.setVisibility(current()!=null&&current().video?View.VISIBLE:View.GONE);surface.setLayoutParams(new LinearLayout.LayoutParams(-1,pip?-1:dp(200)));renderQueue();}
    protected void onResume(){super.onResume();active=true;handler.removeCallbacks(tick);handler.post(tick);}
    protected void onPause(){super.onPause();if(!isInPictureInPictureMode()){active=false;handler.removeCallbacks(tick);}}
    protected void onDestroy(){active=false;handler.removeCallbacksAndMessages(null);worker.shutdown();super.onDestroy();}
    public void surfaceCreated(SurfaceHolder h){if(PlaybackService.instance!=null)PlaybackService.instance.attach(h);}
    public void surfaceChanged(SurfaceHolder h,int f,int w,int height){if(PlaybackService.instance!=null)PlaybackService.instance.attach(h);}
    public void surfaceDestroyed(SurfaceHolder h){if(PlaybackService.instance!=null)PlaybackService.instance.attach(null);}
    private void toast(String message){if(!isDestroyed())Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
    private void seed(){if(getSharedPreferences("library",0).getBoolean("seeded",false))return;String[] names={"First Light","नई सुबह","ਨਵਾਂ ਸਵੇਰਾ"};String[] langs={"English","Hindi","Punjabi"};String[] words={"[00:00.00]Original instrumental · lyrics to read along\n[00:03.00]A little light, a brand new day\n[00:07.00]We find our rhythm on the way\n[00:11.00]The open sky is ours to see\n[00:15.00]A quiet song for you and me","[00:00.00]मौलिक वाद्य संगीत · साथ पढ़ने के बोल\n[00:03.00]नई सुबह का नया उजाला\n[00:07.00]चलते जाएँ सपना प्यारा\n[00:11.00]खुला गगन है राह हमारी\n[00:15.00]धुन में है मुस्कान तुम्हारी","[00:00.00]ਮੌਲਿਕ ਸਾਜ਼ੀ ਧੁਨ · ਨਾਲ ਪੜ੍ਹਨ ਲਈ ਬੋਲ\n[00:03.00]ਨਵਾਂ ਸਵੇਰਾ ਨਵੀਂ ਉਡਾਰੀ\n[00:07.00]ਮਿੱਠੀ ਧੁਨ ਹੈ ਸਭ ਦੀ ਪਿਆਰੀ\n[00:11.00]ਖੁੱਲ੍ਹਾ ਅੰਬਰ ਰਾਹ ਦਿਖਾਵੇ\n[00:15.00]ਹਰ ਇਕ ਦਿਲ ਮੁਸਕਾਨ ਸਜਾਵੇ"};try{for(int i=0;i<3;i++){File f=new File(getFilesDir(),"demo"+i+".ogg");try(InputStream in=getAssets().open("demo"+i+".ogg");OutputStream out=new FileOutputStream(f)){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))!=-1)out.write(buffer,0,count);}Track t=new Track();t.title=names[i];t.artist="Mustang Originals";t.language=langs[i];t.lyrics=words[i];t.credit="Original instrumental and original reading lyrics · no recorded vocals · CC0";t.sources.put("Original",Uri.fromFile(f).toString());library.add(t);}Track demo=new Track();demo.title="Mustang Motion";demo.artist="Mustang Originals";demo.language="Instrumental";demo.video=true;demo.lyrics="Original instrumental — no sung lyrics.";demo.credit="Original generated test animation and music · CC0";
for(String size:new String[]{"180","360"}){File f=new File(getFilesDir(),"demo"+size+".mp4");try(InputStream in=getAssets().open("demo"+size+".mp4");OutputStream out=new FileOutputStream(f)){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))!=-1)out.write(buffer,0,count);}demo.sources.put(size+"p",Uri.fromFile(f).toString());}library.add(demo);
getSharedPreferences("library",0).edit().putBoolean("seeded",true).apply();}catch(Exception e){toast("Demo could not load. Import your own files.");}}
}
